from __future__ import annotations

from .demo import DEMO_ACCOUNTS, DEMO_ACCOUNTS_BY_EMAIL, DEMO_PASSWORD
from .dependencies import get_current_user, require_roles
from .ports import AuthRepository, SupabaseAuthClient
from .repositories import (
    InMemoryAuthRepository,
    PostgresAuthRepository,
    auth_schema_sql,
)
from .routes import router
from .schemas import (
    AcceptInviteRequest,
    AuthOrganizationResponse,
    AuthProfileRecord,
    DemoLoginRequest,
    DemoAccountRecord,
    InviteCreateRequest,
    LoginRequest,
    LoginResponse,
    MessageResponse,
    OrganizationInviteResponse,
    PublicDemoAccount,
    RefreshSessionRequest,
    Role,
    SupabaseAuthSession,
    SupabaseAuthUser,
    UserProfile,
)
from .services import (
    accept_user_invite,
    authenticate_demo_account,
    authenticate_demo_user,
    authenticate_user,
    create_session_token,
    create_user_invite,
    get_auth_provider_mode,
    get_auth_repository,
    get_current_user_from_authorization,
    get_supabase_auth_client,
    is_demo_login_enabled,
    list_public_demo_accounts,
    list_user_invites,
    logout_user_from_authorization,
    refresh_auth_session,
    require_role,
    reset_demo_sessions_for_tests,
)
from .supabase_client import SupabaseAuthRestClient

__all__ = [
    "AuthOrganizationResponse",
    "AuthProfileRecord",
    "AuthRepository",
    "AcceptInviteRequest",
    "DEMO_ACCOUNTS",
    "DEMO_ACCOUNTS_BY_EMAIL",
    "DEMO_PASSWORD",
    "DemoLoginRequest",
    "DemoAccountRecord",
    "InMemoryAuthRepository",
    "InviteCreateRequest",
    "LoginRequest",
    "LoginResponse",
    "MessageResponse",
    "OrganizationInviteResponse",
    "PostgresAuthRepository",
    "PublicDemoAccount",
    "RefreshSessionRequest",
    "Role",
    "SupabaseAuthClient",
    "SupabaseAuthRestClient",
    "SupabaseAuthSession",
    "SupabaseAuthUser",
    "UserProfile",
    "auth_schema_sql",
    "accept_user_invite",
    "authenticate_demo_account",
    "authenticate_demo_user",
    "authenticate_user",
    "create_session_token",
    "create_user_invite",
    "get_auth_provider_mode",
    "get_auth_repository",
    "get_current_user",
    "get_current_user_from_authorization",
    "get_supabase_auth_client",
    "is_demo_login_enabled",
    "list_public_demo_accounts",
    "list_user_invites",
    "logout_user_from_authorization",
    "refresh_auth_session",
    "require_role",
    "require_roles",
    "router",
    "reset_demo_sessions_for_tests",
]
